version: '3.8'

services:
  app:
    image: devsecops-springboot:latest
    environment:
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/devsecops
      SPRING_DATASOURCE_USERNAME: root
    depends_on:
      - db
    networks:
      - devsecops-network
    ports:
      - "8280:8080"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: devsecops
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - devsecops-network

volumes:
  mysql_data:

networks:
  devsecops-network:
    driver: bridge
